name: GlintSMP
version: 'v0.0.1'
main: com.glintsmp.emotion.GlintSMP
api-version: '1.21'

commands:
  Emotion:
    description: Manage emotions
    usage: /Emotion <subcommand>
    aliases: [emt]
    permission: glintsmp.staff