name: GlintSMP
version: 'v0.0.2'
main: com.glintsmp.emotion.GlintSMP
api-version: '1.21'

commands:
  Emotion:
    description: Manage emotions
    usage: /Emotion <subcommand>
    aliases: [emt, emotion]
    permission: glint.staff
  Core:
    description: Manage emotions
    usage: /Core <subcommand>
    aliases: [ C ]
    permission: glint.staff

  Trust:
    description: Trust System
    usage: /trust <subcommand>
    aliases: [t, Team]
  Ability:
    description: ability related commands
    usage: /Ability <subcommand>