name: GlintSMP
version: 'v0.0.2'
main: com.glintsmp.emotion.GlintSMP
api-version: '1.21'

commands:
  Emotion:
    description: Manage emotions
    usage: /Emotion <subcommand>
    aliases: [emt, emotion]
    permission: glint.staff
  Core:
    description: Manage emotions
    usage: /Core <subcommand>
    aliases: [ C ]
    permission: glint.staff
  Ghost:
    description: Manage the ghost system
    usage: /Ghost <subcommand>
    permission: glint.staff
  Testing:
    description: All the commands to test random stuff
    usage: /Testing <subcommand>
    permission: glint.op

  Trust:
    description: Trust System
    usage: /trust <subcommand>
    aliases: [t, Team]
  Ability:
    description: ability related commands
    usage: /Ability <subcommand>
  Life:
    description: Manage the lives
    usage: /Life <subcommand>
  Item:
    description: Item related commands
    usage: /Item <subcommand>